### ISSUE TITLE
환경구축

### ISSUE THREAD

**Issue by ghdi6211** [ghdi6211/TimeSyncer#1]
#  :book: 背景
### TimeSyncer어플리케이션 개발에 필요한 FE의 환경을 구축한다.
#  :gift: 得られるもの
개발에 앞어서 필요한 프레임워크, 라이브러리등을 결정및 설치
#  :white_check_mark: 完了条件

- [x] 로컬환경에서 "Hello World"를 표시

#  :clipboard: タスク

- [x] 리포지토리 개설
- [x] 프레임워크 결정및 설치
- [x] 라이브러리 결정및 설치
- [x] Lint 설치및 설정

#  :warning: 懸念点

#  :memo: その他
